swingwizard/app/base/__init__.py
from flask import Blueprint

bp = Blueprint('base', __name__)

from app.base import routes

swingwizard/app/base/routes.py
from app import *
from app.base import *
from app.helpers import *
from app.models import User
from app.auth.forms import *
from flask import *
from io import BytesIO
from fastai import *
from fastai.vision import *
from flask_login import current_user,login_user,logout_user,login_required
from werkzeug.urls import url_parse



@bp.route('/')
@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('base.user',username=current_user.username))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('base.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('base.user',username=current_user.username)
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)


@bp.route('/logout')
def logout():
    path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
    if os.path.exists(path):
      if len(get_files(path))>0:
        for x in get_files(path): os.remove(x)
      os.rmdir(path)
    logout_user()
    return redirect(url_for('base.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('base.user'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Registered')
        return redirect(url_for('base.login'))
    return render_template('register.html', title='Register', form=form)


# @bp.route('/')
# @bp.route('/home/<username>', methods=['GET', 'POST'])
# @login_required
# def home(username):
#   user = User.query.filter_by(username=username).first_or_404()
#   path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
#   if not os.path.exists(path): os.makedirs(path)
#   return render_template('user.html',user=user)


@bp.route('/home/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
    if not os.path.exists(path): os.makedirs(path)
    return render_template('user.html', user=user)


@bp.route('/inputvideo/<username>',methods=['GET','POST'])
@login_required
def input_video(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  if not os.path.exists(path): os.makedirs(path)
  if os.path.exists(path):
    if len(get_files(path))>0:
      for x in get_files(path): os.remove(x)
  if request.method == 'POST':
    fname = get_filename(path,save=True)
    get_frames(fname)
    frames = get_image_files(path)
    return redirect(url_for('base.uploads_video',username=current_user.username))
  return render_template('inputVideo.html',user=user,username=current_user.username)

@bp.route('/inputimage/<username>',methods=['GET','POST'])
@login_required
def input_image(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  if not os.path.exists(path): os.makedirs(path)
  if os.path.exists(path):
    if len(get_files(path))>0:
      for x in get_files(path): os.remove(x)
  if request.method == 'POST':
    fname = get_filename(path,save=True)
    frames = get_image_files(path)
    return redirect(url_for('base.uploads_image',username=current_user.username))
  return render_template('inputImage.html',user=user)


@bp.route('/uploadsvideo/<username>')
@login_required
def uploads_video(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  frames = get_image_files(path)
  lst = [re.compile(r'([^/]+$)').search(str(x)).group(1) for x in frames]
  fnames = [f"{current_user.username}/{x}" for x in lst]
  return render_template('uploadVideo.html',user=user,
                         username=current_user.username,
                         f1=fnames[0],f2=fnames[1],f3=fnames[2],f4=fnames[3],f5=fnames[4])

@bp.route('/uploadsimage/<username>')
@login_required
def uploads_image(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  frames = get_image_files(path)
  lst = [re.compile(r'([^/]+$)').search(str(x)).group(1) for x in frames]
  fnames = [f"{current_user.username}\\{x}" for x in lst]
  return render_template('uploadImage.html',user=user,
                         username=current_user.username,f1=fnames[0])


@bp.route('/resultsvideo/<username>')
@login_required
def results_video(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  if not os.path.exists(path): os.makedirs(path)
  frames = get_image_files(path)
  lst = [re.compile(r'([^/]+$)').search(str(x)).group(1) for x in frames]
  fnames = [f"{current_user.username}/{x}" for x in lst]
  f1=fnames[0];p1,c1=get_results(frames,0)
  f2=fnames[1];p2,c2=get_results(frames,1)
  f3=fnames[2];p3,c3=get_results(frames,2)
  f4=fnames[3];p4,c4=get_results(frames,3)
  f5=fnames[4];p5,c5=get_results(frames,4)
  return render_template('resultsVideo.html',user=user,
                         f1=f1,p1=p1,c1=c1,
                         f2=f2,p2=p2,c2=c2,
                         f3=f3,p3=p3,c3=c3,
                         f4=f4,p4=p4,c4=c4,
                         f5=f5,p5=p5,c5=c5)


@bp.route('/resultsimage/<username>')
@login_required
def results_image(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  if not os.path.exists(path): os.makedirs(path)
  frames = get_image_files(path)
  lst = [re.compile(r'([^/]+$)').search(str(x)).group(1) for x in frames]
  fnames = [f"{current_user.username}/{x}" for x in lst]
  f1=fnames[0];p1,c1=get_results(frames,0)
  return render_template('resultsImage.html',user=user,
                         username=current_user.username,
                         f1=f1,p1=p1,c1=c1)


@bp.route('/deletinguploads/<username>')
@login_required
def deleting_uploads(username):
  user = User.query.filter_by(username=username).first_or_404()
  path = Path(str(basedir+f'/app/static/uploads/{current_user.username}'))
  if not os.path.exists(path): os.makedirs(path)
  for f in get_files(path):
    os.remove(f)
  return redirect(url_for('base.user',username=current_user.username,user=user))

swingwizard/app/templates/base.html
<!doctype html>
<html lang="en">
<!-- -----------------------------------    Head    -------------------------------------------- -->
  <head>
    {% block head %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
      <meta name="generator" content="Jekyll v3.8.5">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="{{url_for('static', filename='client.js')}}"></script>
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <title>{% block title %}{% endblock title %} - Swing Wizard</title>

    {% endblock head %}
  </head>

<!-- -----------------------------------    Body    -------------------------------------------- -->

  <body>
    {% block body %}

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

      <header>
        {% block navbar %}
          <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <!-- <a class="navbar-brand" href="https://github.com/pattyhendrix/">Hendrix</a> -->
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{url_for('base.deleting_uploads',username=current_user.username)}}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if current_user.is_anonymous %}
                  <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('base.login')}}">Login <span class="sr-only">(current)</span></a>
                  </li>
                {% else %}
                  <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('base.logout')}}">Logout <span class="sr-only">(current)</span></a>
                  </li>
                {% endif %}
          </nav>
        {% endblock navbar %}
      </header>

<!-- -----------------------------------    Main    -------------------------------------------- -->

      <main role="main">
        {% block main %}

<!-- -----------------------------------    Main1    -------------------------------------------- -->

          <section class="jumbotron text-center">
            {% block secJumbo %}
              <div class="container">
                <br>
                <br>
                <h1 class="jumbotron-heading">Swing Wizard</h1>
                <br>
                <p>
                  {% block buttonsOrResults %}

                  {% endblock buttonsOrResults%}
                </p>
              </div>
            {% endblock secJumbo %}
          </section>

<!-- -----------------------------------    Main2    -------------------------------------------- -->

          <section class="Results text-center">
            {% block secResults %}
              <div class="container marketing">

                {% block results %}

                {% endblock results %}
              </div>

            {% endblock secResults%}
          </section>

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

        {% endblock main%}
      </main>

<!-- -----------------------------------    Footer    -------------------------------------------- -->

      <footer class="text-muted">
        {% block footer %}
          <div class="container">
            <p class="float-right">
              <a href="#">Back to top</a>
            </p>
            <p>&copy; <a href="https://github.com/pattyhendrix/">pattyhendrix</a> & <a href="https://www.instagram.com/wagssworld/">wagssworld</a></p>
          </div>
        {% endblock footer %}
      </footer>


    {% endblock body %}
  </body>
</html>

swingwizard/app/templates/home.html
{% extends "base.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->

      <title>{% block title %}Home{% endblock title %} - Swing Wizard</title>

<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->

          <section class="jumbotron text-center">
            {% block secJumbo %}
              <div class="container">
                <br>
                <br>
                <h1 class="jumbotron-heading">Swing Wizard</h1>
                <br>
                <p>
                  {% block buttonsOrResults %}
                  <a href="{{ url_for('base.user', username=current_user.username) }}" class="btn btn-primary my-2">Choose Input Type</a>
                  {% endblock buttonsOrResults%}
                </p>
              </div>
            {% endblock secJumbo %}
          </section>

<!-- -----------------------------------    Main2    -------------------------------------------- -->

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/inputImage.html
{% extends "base.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Input{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->

                  {% block buttonsOrResults %}
                    <form method=post enctype=multipart/form-data>
                      <input type=file name=file id='file-input' onchange='showFilePicked(this)'>
                      <button href="{{url_for('base.uploads_image',username=current_user.username)}}" type=submit value=Upload>Upload</button>
                    </form>
                      <div class='upload-label no-display'>
                        <label class='no-display' id='upload-label'></label>
                      </div>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/inputVideo.html
{% extends "base.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Input{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->

                  {% block buttonsOrResults %}
                    <form method=post enctype=multipart/form-data>
                      <input type=file name=file id='file-input' onchange='showFilePicked(this)'>
                      <button href="{{url_for('base.uploads_video',username=current_user.username)}}" type=submit value=Upload>Upload</button>
                    </form>
                      <div class='upload-label no-display'>
                        <label class='no-display' id='upload-label'></label>
                      </div>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/login.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Login{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->
                  {% block buttonsOrResults %}
                    {% block signin %}
                            <h1>Sign In</h1>
                              <form action="" method="post" novalidate>
                                  {{ form.hidden_tag() }}
                                  <p>
                                      {{ form.username.label }}<br>
                                      {{ form.username(size=32) }}<br>
                                      {% for error in form.username.errors %}
                                      <span style="color: red;">[{{ error }}]</span>
                                      {% endfor %}
                                  </p>
                                  <p>
                                      {{ form.password.label }}<br>
                                      {{ form.password(size=32) }}<br>
                                      {% for error in form.password.errors %}
                                      <span style="color: red;">[{{ error }}]</span>
                                      {% endfor %}
                                  </p>
                                  <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                                  <p>{{ form.submit() }}</p>
                              </form>
                    {% endblock %}

                    {% block sigin2 %}

                   <br><p><a href="{{ url_for('base.register') }}">Register</a></p>

                   {% endblock %}
                  {% endblock buttonsOrResults%}
<!-- -----------------------------------    Main2    -------------------------------------------- -->

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/resultsImage.html
{% extends "uploadImage.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Results{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->

                  {% block buttonsOrResults %}
                    <h2>Results:</h2>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

                  {% block result1 %}{{p1}}<br>0-100: {{c1}}{% endblock %}

                  <hr class="featurette-divider">

                  {% block resultsButton %}
                    <a href="{{url_for('base.deleting_uploads',username=current_user.username)}}"class="btn btn-secondary my-2">Home</a>
                  {% endblock %}

                  <hr class="featurette-divider">

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/resultsVideo.html
{% extends "uploadVideo.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Results{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->

                  {% block buttonsOrResults %}
                    <h2>Results:</h2>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

                  {% block result1 %}{{p1}}<br>0-100: {{c1}}{% endblock %}

                  {% block result2 %}{{p2}}<br>0-100: {{c2}}{% endblock %}

                  {% block result3 %}{{p3}}<br>0-100: {{c3}}{% endblock %}

                  {% block result4 %}{{p4}}<br>0-100: {{c4}}{% endblock %}

                  {% block result5 %}{{p5}}<br>0-100: {{c5}}{% endblock %}

                  <hr class="featurette-divider">

                  {% block resultsButton %}
                    <a href="{{url_for('base.deleting_uploads',username=current_user.username)}}"class="btn btn-secondary my-2">Home</a>
                  {% endblock %}

                  <hr class="featurette-divider">

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/uploadImage.html
{% extends "base.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Uploads{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->


                  {% block buttonsOrResults %}
                    <h2>Uploads:</h2>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

          <div class="container marketing">
                {% block results %}

                    <hr class="featurette-divider">
                      <div class="row featurette">
                        <div class="col-md-6">
                          <img src="..\\static\\uploads\\{{f1}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                        </div>
                      </div>

                  {% block result1 %}{% endblock %}


                  <hr class="featurette-divider">

                  {% block resultsButton %}
                    <a href="{{url_for('base.results_image',username=current_user.username)}}"class="btn btn-secondary my-2">Analyze</a>
                  {% endblock resultsButton%}

                  <hr class="featurette-divider">

                {% endblock results %}
              </div>



<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/uploadVideo.html
{% extends "base.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->
      <title>{% block title %}Uploads{% endblock title %} - Swing Wizard</title>
<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->


                  {% block buttonsOrResults %}
                    <h2>Uploads:</h2>
                  {% endblock buttonsOrResults%}

<!-- -----------------------------------    Main2    -------------------------------------------- -->

          <div class="container marketing">
                {% block results %}

                    <hr class="featurette-divider">
                      <div class="row featurette">
                        <div class="col-md-6">
                          <img src="../static/uploads/{{f1}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                        </div>
                      </div>

                  {% block result1 %}{% endblock %}


                  <hr class="featurette-divider">
                    <div class="row featurette">
                      <div class="col-md-6">
                        <img src="../static/uploads/{{f2}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                      </div>
                    </div>

                  {% block result2 %}{% endblock %}

                    <hr class="featurette-divider">
                      <div class="row featurette">
                        <div class="col-md-6">
                          <img src="../static/uploads/{{f3}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                        </div>
                      </div>

                  {% block result3 %}{% endblock %}

                  <hr class="featurette-divider">
                    <div class="row featurette">
                      <div class="col-md-6">
                        <img src="../static/uploads/{{f4}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                      </div>
                    </div>

                  {% block result4 %}{% endblock %}

                    <hr class="featurette-divider">
                      <div class="row featurette">
                        <div class="col-md-6">
                          <img src="../static/uploads/{{f5}}" id='image-picked' class="mx-auto" alt="" width="400" height="300" preserveAspectRatio="xMidYMid slice"/>
                        </div>
                      </div>

                  {% block result5 %}{% endblock %}

                  <hr class="featurette-divider">

                  {% block resultsButton %}
                    <a href="{{url_for('base.results_video',username=current_user.username)}}"class="btn btn-secondary my-2">Analyze</a>
                  {% endblock %}

                  <hr class="featurette-divider">

                {% endblock results %}
              </div>



<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->

swingwizard/app/templates/user.html
{% extends "home.html" %}

<!-- -----------------------------------    Head    -------------------------------------------- -->

<!-- -----------------------------------    Body    -------------------------------------------- -->

<!-- ----------------------------------    Navbar    ------------------------------------------- -->

<!-- -----------------------------------    Main    -------------------------------------------- -->

<!-- -----------------------------------    Main1    -------------------------------------------- -->
                  {% block buttonsOrResults %}
                    <a href="{{url_for('base.input_image',username=current_user.username)}}" class="btn btn-primary my-2">Image</a>
                    <a href="{{url_for('base.input_video',username=current_user.username)}}" class="btn btn-secondary my-2">Video</a>
                    </form>
                      <div class='upload-label no-display'>
                        <label class='no-display' id='upload-label'></label>
                      </div>
                  {% endblock buttonsOrResults%}
<!-- -----------------------------------    Main2    -------------------------------------------- -->

<!-- -----------------------------------    test    -------------------------------------------- -->

<!-- -----------------------------------    EndMain    -------------------------------------------- -->

<!-- -----------------------------------    Footer    -------------------------------------------- -->